/// <reference types="@capacitor-firebase/messaging" />
import type { CapacitorConfig } from '@capacitor/cli'

const config: CapacitorConfig = {
  appId: 'com.inmaculada.music',
  appName: 'Inmaculada Music',
  // This folder is generated by `npm run build` (Next.js static export)
  webDir: 'out',
  // Default Capacitor Android scheme is https://localhost — fetching http://localhost:3000/api
  // is mixed active content and often blocked as "Failed to fetch" even with allowMixedContent.
  server: {
    androidScheme: 'http',
  },
  android: {
    allowMixedContent: true,
    webContentsDebuggingEnabled: true,
  },
  plugins: {
    FirebaseMessaging: {
      presentationOptions: ['badge', 'sound', 'alert'],
    },
  },
}

export default config

